# Preprocessing Data
## Data POI

In [5]:
import pandas as pd

In [191]:
# Import Data
POI = pd.read_excel("D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Raw Data/Data-POI.xlsx")
POI.head()

,FID,ACTADDRESS,OBJECT,PROVINSI,KABKOT,KECAMATAN,DESA,IDDESA,CLASS,SUBCLASS,...,KABKOTNO,KECNO,DESANO,JMLH_RUMAH,TIPE_RUMAH,DEVELOPER,KET2,LONG,LAT,TGL_ADD
0,92,Jl. Ahmad Yani,SPBU Pertamina 64.714.05,KALIMANTAN SELATAN,BALANGAN,BATU MANDI,BATU MANDI,6311020012,Amenity,Petrol Stations,...,11,20,12,,,,,115.428393,-2.418616,2021-06-14
1,94,Jl. Ahmad Yani,SPBU Pertamina 64.714.08,KALIMANTAN SELATAN,BALANGAN,BATU MANDI,BANUA HANYAR,6311020017,Amenity,Petrol Stations,...,11,20,17,,,,,115.458010,-2.381378,2021-06-14
2,98,Jl. Ahmad Yani,SPBU Pertamina 64.714.02,KALIMANTAN SELATAN,BALANGAN,PARINGIN,PARINGIN KOTA,6311040013,Amenity,Petrol Stations,...,11,40,13,,,,,115.465953,-2.319457,2021-06-14
3,8647,"Dayak Pitap, Awayan, Balangan, Kalimantan Selatan",Gunung Banyutawar,KALIMANTAN SELATAN,BALANGAN,TEBING TINGGI,KAMBIYAIN,6311031012,Tourism,Vantage Point,...,11,31,12,,,,,115.733010,-2.566660,2020-01-28
4,8971,Jl. Datu Mantir Rt. 01,SD NEGERI KAMBIYAIN,KALIMANTAN SELATAN,BALANGAN,TEBING TINGGI,AJUNG,6311031011,Amenity,Elementary School,...,11,31,11,,,,,115.612400,-2.495900,2020-01-28

In [192]:
from collections import defaultdict

counts = defaultdict(lambda: defaultdict(int))
for kabkot, subclass in zip(POI['KABKOT'], POI['SUBCLASS']):
    counts[kabkot][subclass] += 1

rows = []
for kabkot, subclass_counts in counts.items():
    for subclass, count in subclass_counts.items():
        rows.append({'KABKOT': kabkot, 'SUBCLASS': subclass, 'COUNT': count})

POI_df = pd.DataFrame(rows)
POI_df.head()

     KABKOT            SUBCLASS  COUNT
0  BALANGAN     Petrol Stations      3
1  BALANGAN       Vantage Point      2
2  BALANGAN   Elementary School    197
3  BALANGAN  Government Offices    156
4  BALANGAN  Junior High School     39

In [193]:
POI_pivot = POI_df.pivot(index='KABKOT', columns='SUBCLASS', values='COUNT').fillna(0).astype(int)
POI_pivot.head()

SUBCLASS,Airport,Auto Parts/Auto Accessories,Banks/Financial Services,Beauty Salon/Barber,Beauty Service Center/Cosmetic,Books/Office Equipment,Bureau Of Monks,Bus Station,Car Care,Car Dealership,...,Swimming Pool,Tourism Site,Tourist Office,Travel Agency,Tutoring/Computer/Language,University/College,Vantage Point,Warehouse,Watches/Glasses/Optics,Zoo
KABKOT,,,,,,,,,,,,,,,,,,,,,
BALANGAN,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
BANJAR,0,0,0,0,1,0,0,0,0,9,...,0,4,0,0,0,1,12,1,0,0
BARITO KUALA,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
HULU SUNGAI SELATAN,0,0,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
HULU SUNGAI TENGAH,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [194]:
# Reset index untuk membuat KABKOT menjadi kolom
POI_pivot = POI_pivot.reset_index()

# Mengganti nama kolom 'index' (jika ada) menjadi 'KABKOT'
POI_pivot = POI_pivot.rename(columns={'index': 'KABKOT'})

POI_pivot.head()

SUBCLASS,KABKOT,Airport,Auto Parts/Auto Accessories,Banks/Financial Services,Beauty Salon/Barber,Beauty Service Center/Cosmetic,Books/Office Equipment,Bureau Of Monks,Bus Station,Car Care,...,Swimming Pool,Tourism Site,Tourist Office,Travel Agency,Tutoring/Computer/Language,University/College,Vantage Point,Warehouse,Watches/Glasses/Optics,Zoo
0,BALANGAN,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
1,BANJAR,0,0,0,0,1,0,0,0,0,...,0,4,0,0,0,1,12,1,0,0
2,BARITO KUALA,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,HULU SUNGAI SELATAN,0,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
4,HULU SUNGAI TENGAH,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [195]:
# Mengganti nilai di kolom 'KABKOT'
POI_pivot['KABKOT'] = POI_pivot['KABKOT'].replace({
    'KOTA BANJAR BARU': 'KOTA BANJARBARU',
    'KOTA BARU': 'KOTABARU'
})

In [196]:
POI_pivot.to_excel('D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Processed Data/Data POI.xlsx')

## Data Potensi Wilayah

In [197]:
DPW = pd.read_excel("D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Raw Data/Data Potensi Wilayah.xlsx")
DPW.head()

,KODE,NAMA,JUMLAH DESA,JUMLAH DESA TERDATA,JUMLAH LUAS WILAYAH,JUMLAH PENETAPAN BATAS,JUMLAH PETA BATAS
0,6301,KAB TANAH LAUT,135,46,1356790.000,22,40
1,6302,KAB KOTABARU,202,142,1958382.000,109,117
2,6303,KAB BANJAR,290,51,630.843,31,41
3,6304,KAB BARITO KUALA,201,121,108.388,78,108
4,6305,KAB TAPIN,135,131,2460916.000,90,115

In [198]:
# Menghapus kolom KODE
DPW = DPW.drop(columns=['KODE'])

# Menghapus kata "KAB" dari kolom NAMA dan mengganti nama kolom menjadi KABKOT
DPW['KABKOT'] = DPW['NAMA'].str.replace('KAB ', '', regex=False)
DPW = DPW.drop(columns=['NAMA'])
DPW.head()

,JUMLAH DESA,JUMLAH DESA TERDATA,JUMLAH LUAS WILAYAH,JUMLAH PENETAPAN BATAS,JUMLAH PETA BATAS,KABKOT
0,135,46,1356790.000,22,40,TANAH LAUT
1,202,142,1958382.000,109,117,KOTABARU
2,290,51,630.843,31,41,BANJAR
3,201,121,108.388,78,108,BARITO KUALA
4,135,131,2460916.000,90,115,TAPIN

In [199]:
DPW.to_excel('D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Processed Data/Data Potensi Wilayah.xlsx')

## Data Penduduk Per Kabupaten

In [200]:
Penduduk = pd.read_excel("D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Raw Data/Penduduk Per Kabupaten.xlsx")
Penduduk.head()

      Kabupaten  Laki-Laki  Perempuan   Total
0    TANAH LAUT     186.62     178.37  364.98
1      KOTABARU     176.80     166.88  343.68
2        BANJAR     303.10     297.54  600.64
3  BARITO KUALA     167.67     163.32  330.99
4         TAPIN     100.48      98.39  198.87

In [201]:
Penduduk['KABKOT'] = Penduduk['Kabupaten']
Penduduk = Penduduk.drop(columns=['Kabupaten','Total'])

# Mengganti nilai di kolom 'KABKOT'
Penduduk['KABKOT'] = Penduduk['KABKOT'].replace({
    'KOTA BANJAR BARU': 'KOTA BANJARBARU'
})

Penduduk.head()

   Laki-Laki  Perempuan        KABKOT
0     186.62     178.37    TANAH LAUT
1     176.80     166.88      KOTABARU
2     303.10     297.54        BANJAR
3     167.67     163.32  BARITO KUALA
4     100.48      98.39         TAPIN

In [202]:
Penduduk.to_excel('D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Processed Data/Penduduk Per Kabupaten.xlsx')

## Jarak Ibukota Kabupaten ke Provinsi

In [203]:
Jarak = pd.read_excel("D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Raw Data/Jarak Ibukota ke Provinsi.xlsx")
Jarak.head()

                  Lokasi/Ibukota  Jarak (Km)
0    Kab. Tanah Laut (Pelaihari)          65
1       Kab. Kotabaru (Kotabaru)         305
2        Kab. Banjar (Martapura)          40
3  Kab. Barito Kuala (Marabahan)          45
4            Kab. Tapin (Rantau)         113

In [204]:
# Mengubah huruf menjadi uppercase dan menghapus "KAB."
Jarak['Lokasi/Ibukota'] = Jarak['Lokasi/Ibukota'].str.upper().str.replace('KAB. ', '', regex=False)

# Menghapus teks dalam kurung
Jarak['Lokasi/Ibukota'] = Jarak['Lokasi/Ibukota'].str.replace(r'\(.*?\)', '', regex=True)

# Membersihkan spasi ekstra
Jarak['Lokasi/Ibukota'] = Jarak['Lokasi/Ibukota'].str.strip()

# Mengubah nama kolom
Jarak['KABKOT'] = Jarak['Lokasi/Ibukota']
Jarak = Jarak.drop(columns=['Lokasi/Ibukota'])
Jarak.head()

   Jarak (Km)        KABKOT
0          65    TANAH LAUT
1         305      KOTABARU
2          40        BANJAR
3          45  BARITO KUALA
4         113         TAPIN

In [205]:
Jarak.to_excel('D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Processed Data/Jarak Ibukota ke Provinsi.xlsx')

## Jumlah Akomodasi Hotel

In [206]:
Hotel = pd.read_excel("D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Raw Data/Akomodasi Hotel.xlsx")
Hotel.head()

,Lokasi/Tahun,Hotel (2014),Kamar (2014),Tempat Tidur (2014),Hotel (2015),Kamar (2015),Tempat Tidur (2015),Hotel (2022),Kamar (2022),Tempat Tidur (2022)
0,Tanah Laut,13,180,351,11,176,337,1,45,67
1,Kotabaru,28,421,593,40,537,699,2,81,127
2,Banjar,15,271,641,17,456,890,6,572,837
3,Barito Kuala,3,30,57,4,63,123,-,-,-
4,Tapin,8,99,161,11,136,223,-,-,-

In [207]:
# Mengubah huruf di kolom 'Lokasi/Tahun' menjadi uppercase
Hotel['Lokasi/Tahun'] = Hotel['Lokasi/Tahun'].str.upper()

# Membuat DataFrame baru dengan data tahun 2022
Hotel_2022 = Hotel[['Lokasi/Tahun', 'Hotel (2022)', 'Kamar (2022)', 'Tempat Tidur (2022)']]

# Menghapus "(2022)" dari nama kolom
Hotel_2022 = Hotel_2022.rename(columns={
    'Hotel (2022)': 'Hotel',
    'Kamar (2022)': 'Kamar',
    'Tempat Tidur (2022)': 'Tempat Tidur'
})

# Mengganti nilai di kolom 'Lokasi/Tahun'
Hotel_2022['Lokasi/Tahun'] = Hotel_2022['Lokasi/Tahun'].replace({
    'BANJARMASIN': 'KOTA BANJARMASIN',
    'BANJARBARU': 'KOTA BANJARBARU'
})

# Mengganti "-" dengan 0
Hotel_2022 = Hotel_2022.replace('-', 0)

# Mengubah tipe data kolom menjadi integer
for col in ['Hotel', 'Kamar', 'Tempat Tidur']:
    Hotel_2022[col] = Hotel_2022[col].astype(int)

# Mengubah nama kolom
Hotel_2022['KABKOT'] = Hotel_2022['Lokasi/Tahun']
Hotel_2022 = Hotel_2022.drop(columns=['Lokasi/Tahun'])

# Mengambil kolom KABKOT
kabkot_column = Hotel_2022['KABKOT']

# Menghapus kolom KABKOT dari DataFrame asli
Hotel_2022 = Hotel_2022.drop(columns=['KABKOT'])

# Menambahkan kolom KABKOT ke posisi paling kiri
Hotel_2022.insert(0, 'KABKOT', kabkot_column)

Hotel_2022.head()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13788\2340075330.py:21: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Hotel_2022 = Hotel_2022.replace('-', 0)

         KABKOT  Hotel  Kamar  Tempat Tidur
0    TANAH LAUT      1     45            67
1      KOTABARU      2     81           127
2        BANJAR      6    572           837
3  BARITO KUALA      0      0             0
4         TAPIN      0      0             0

In [208]:
Hotel_2022.to_excel('D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Processed Data/Akomodasi Hotel.xlsx')

## Jumlah Kunjungan Wisata

In [209]:
Kunjungan = pd.read_excel("D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Raw Data/Jumlah Kunjungan Wisata.xlsx")
Kunjungan.head()

,Lokasi/Tahun,2012 - Total,2013 - Total,2014 - Total,2016 - Total,2018 - Total,2019 - Total,2020 - Nusantara,2020- Mancanegara,2020 - Total,2021 - Nusantara,2021- Mancanegara,2021 - Total,2022 - Nusantara,2022- Mancanegara,2022 - Total
0,Kab. Tanah Laut,NaN,NaN,NaN,NaN,340362,25263,330241,4,330245,50270,0.0,50270,567506,8,567514
1,Kab. Kotabaru,NaN,NaN,NaN,NaN,541487,335338,421971,83,422054,200628,18.0,200646,763385,67,763452
2,Kab. Banjar,NaN,NaN,NaN,NaN,7173830,6925839,5494048,260,5494308,635110,0.0,635110,2104383,1063,2105446
3,Kab. Barito Kuala,NaN,NaN,NaN,NaN,131883,53636,53550,21,53571,50985,3.0,50988,178044,78,178122
4,Kab. Tapin,NaN,NaN,NaN,NaN,1536130,702911,595478,0,595478,366171,0.0,366171,1727420,19,1727439

In [210]:
print(Kunjungan.columns)

Index(['Lokasi/Tahun', '2012 - Total', '2013 - Total', '2014 - Total',
       '2016 - Total', '2018 - Total', '2019 - Total', '2020 - Nusantara',
       '2020- Mancanegara', '2020 - Total', '2021 - Nusantara',
       '2021- Mancanegara', '2021 - Total', '2022 - Nusantara',
       '2022- Mancanegara', '2022 - Total'],
      dtype='object')

In [211]:
# Menghapus baris terakhir
Kunjungan = Kunjungan.drop(Kunjungan.index[-1])

# Mengubah huruf di kolom 'Lokasi/Tahun' menjadi uppercase dan hapus KAB.
Kunjungan['Lokasi/Tahun'] = Kunjungan['Lokasi/Tahun'].str.upper().str.replace('KAB. ', '', regex=False)

# Membuat DataFrame baru dengan data tahun 2022
Kunjungan_2022 = Kunjungan[['Lokasi/Tahun', '2022 - Nusantara', '2022- Mancanegara']]

# Menghapus "2022 -" dari nama kolom
Kunjungan_2022 = Kunjungan_2022.rename(columns={
    '2022 - Nusantara': 'Nusantara',
    '2022- Mancanegara': 'Mancanegara'
})

# Mengubah nama kolom
Kunjungan_2022['KABKOT'] = Kunjungan_2022['Lokasi/Tahun']
Kunjungan_2022 = Kunjungan_2022.drop(columns=['Lokasi/Tahun'])
Kunjungan_2022.head()

   Nusantara  Mancanegara        KABKOT
0     567506            8    TANAH LAUT
1     763385           67      KOTABARU
2    2104383         1063        BANJAR
3     178044           78  BARITO KUALA
4    1727420           19         TAPIN

In [212]:
Kunjungan_2022.to_excel('D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Processed Data/Kunjungan Wisata.xlsx')

## Jumlah Objek Wisata

In [213]:
Objek = pd.read_excel("D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Raw Data/Jumlah Objek Wisata.xlsx")
Objek.head()

,Lokasi/Tahun,Alam (2019),Buatan (2019),Budaya (2019),Total (2019),Alam (2020),Buatan (2020),Budaya (2020),Total (2020),Alam (2021),Buatan (2021),Budaya (2021),Total (2021),Alam (2022),Buatan (2022),Budaya (2022),Religi (2022),Kuliner (2022),Total (2022)
0,Kab. Tanah Laut,31,9,9,49,31,9,9,49,48,8.0,15.0,71,26,4.0,NaN,NaN,NaN,30
1,Kab. Kotabaru,90,16,10,116,90,16,10,116,11,NaN,NaN,11,6,NaN,NaN,1.0,NaN,7
2,Kab. Banjar,7,6,35,48,7,6,35,48,46,24.0,37.0,107,14,7.0,NaN,2.0,NaN,23
3,Kab. Barito Kuala,3,4,1,8,3,4,1,8,4,4.0,1.0,9,5,9.0,NaN,1.0,NaN,15
4,Kab. Tapin,5,2,13,20,5,2,13,20,23,12.0,20.0,55,14,4.0,NaN,8.0,1.0,27

In [214]:
print(Objek.columns)

Index(['Lokasi/Tahun', 'Alam (2019)', 'Buatan (2019)', 'Budaya (2019)',
       'Total (2019)', 'Alam (2020)', 'Buatan (2020)', 'Budaya (2020)',
       'Total (2020)', 'Alam (2021)', 'Buatan (2021)', 'Budaya (2021)',
       'Total (2021)', 'Alam (2022)', 'Buatan (2022)', 'Budaya (2022)',
       'Religi (2022)', 'Kuliner (2022)', 'Total (2022)'],
      dtype='object')

In [215]:
import numpy as np
# Menghapus baris terakhir
Objek = Objek.drop(Objek.index[-1])

# Mengubah huruf di kolom 'Lokasi/Tahun' menjadi uppercase dan hapus KAB.
Objek['Lokasi/Tahun'] = Objek['Lokasi/Tahun'].str.upper().str.replace('KAB. ', '', regex=False)

# Membuat DataFrame baru dengan data tahun 2022
Objek_2022 = Objek[['Lokasi/Tahun', 'Alam (2022)', 'Buatan (2022)','Budaya (2022)','Religi (2022)','Kuliner (2022)']]

# Menghapus "(2022)" dari nama kolom
Objek_2022 = Objek_2022.rename(columns={
    'Alam (2022)': 'Alam',
    'Buatan (2022)': 'Buatan',
    'Budaya (2022)': 'Budaya',
    'Religi (2022)': 'Religi',
    'Kuliner (2022)': 'Kuliner'
})

# Mengganti "NaN" dengan 0
Objek_2022 = Objek_2022.replace(np.nan, 0)

# Mengubah nama kolom
Objek_2022['KABKOT'] = Objek_2022['Lokasi/Tahun']
Objek_2022 = Objek_2022.drop(columns=['Lokasi/Tahun'])
Objek_2022.head()

   Alam  Buatan  Budaya  Religi  Kuliner        KABKOT
0    26     4.0     0.0     0.0      0.0    TANAH LAUT
1     6     0.0     0.0     1.0      0.0      KOTABARU
2    14     7.0     0.0     2.0      0.0        BANJAR
3     5     9.0     0.0     1.0      0.0  BARITO KUALA
4    14     4.0     0.0     8.0      1.0         TAPIN

In [216]:
Objek_2022.to_excel('D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Processed Data/Objek Wisata.xlsx')

## Luas Wilayah Berdasarkan Jenis Tanah

In [217]:
Tanah = pd.read_excel("D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Raw Data/Luas Jenis Tanah.xlsx")
Tanah.head()

,Kabupaten,OGH - 2017,OGH - 2018,OGH - 2019,KPMK - 2017,KPMK - 2018,KPMK - 2019,Alluvial - 2017,Alluvial - 2018,Alluvial - 2019,...,Litosol - 2019,Podso-lid - 2017,Podso-lid - 2018,Podso-lid - 2019,Renzina - 2017,Renzina - 2018,Renzina - 2019,Gambut - 2017,Gambut - 2018,Gambut - 2019
0,KALIMANTAN SELATAN,191610,191610,191610,928429,928429,928429,712446,712446,712446,...,86874,1393557,1393557,1393557,19312,19312,19312,280387,280387,280387
1,TANAH LAUT,0,0,0,154250,154250,154250,98868,98868,98868,...,0,26875,26875,26875,0,0,0,7187,7187,7187
2,KOTABARU,42187,42187,42187,95678,95678,95678,114832,114832,114832,...,53437,636139,636139,636139,0,0,0,0,0,0
3,BANJAR,0,0,0,203750,203750,203750,107973,107973,107973,...,2812,109687,109687,109687,0,0,0,46875,46875,46875
4,BARITO KUALA,95049,95049,95049,0,0,0,142573,142573,142573,...,0,0,0,0,0,0,0,0,0,0

In [218]:
print(Tanah.columns)

Index(['Kabupaten', 'OGH - 2017', 'OGH - 2018', 'OGH - 2019', 'KPMK - 2017',
       'KPMK - 2018', 'KPMK - 2019', 'Alluvial - 2017', 'Alluvial - 2018',
       'Alluvial - 2019', 'Latoso - 2017', 'Latoso - 2018', 'Latoso - 2019',
       'Litosol - 2017', 'Litosol - 2018', 'Litosol - 2019',
       'Podso-lid - 2017', 'Podso-lid - 2018', 'Podso-lid - 2019',
       'Renzina - 2017', 'Renzina - 2018', 'Renzina - 2019', 'Gambut - 2017',
       'Gambut - 2018', 'Gambut - 2019'],
      dtype='object')

In [219]:
# Menghapus baris pertama
Tanah = Tanah.drop(Tanah.index[0])

# Membuat DataFrame baru dengan data tahun 2019
Tanah_2019 = Tanah[['Kabupaten', 'OGH - 2019', 'KPMK - 2019', 'Alluvial - 2019', 'Latoso - 2019',
                    'Litosol - 2019', 'Podso-lid - 2019', 'Renzina - 2019', 'Gambut - 2019']]

# Menghapus "- 2019" dari nama kolom
Tanah_2019 = Tanah_2019.rename(columns={
    'OGH - 2019': 'OGH',
    'KPMK - 2019': 'KPMK',
    'Alluvial - 2019': 'Alluvial',
    'Latoso - 2019': 'Latoso',
    'Litosol - 2019': 'Litosol',
    'Podso-lid - 2019': 'Podso-lid',
    'Renzina - 2019': 'Renzina',
    'Gambut - 2019': 'Gambut'
})

# Mengubah nama kolom
Tanah_2019['KABKOT'] = Tanah_2019['Kabupaten']
Tanah_2019 = Tanah_2019.drop(columns=['Kabupaten'])

# Mengganti nilai di kolom 'KABKOT'
Tanah_2019['KABKOT'] = Tanah_2019['KABKOT'].replace({
    'KOTA BANJAR BARU': 'KOTA BANJARBARU'
})

Tanah_2019.head()

,OGH,KPMK,Alluvial,Latoso,Litosol,Podso-lid,Renzina,Gambut,KABKOT
1,0,154250,98868,85750,0,26875,0,7187,TANAH LAUT
2,42187,95678,114832,0,53437,636139,0,0,KOTABARU
3,0,203750,107973,0,2812,109687,0,46875,BANJAR
4,95049,0,142573,0,0,0,0,0,BARITO KUALA
5,0,4062,41250,0,0,48125,0,124058,TAPIN

In [220]:
Tanah_2019.to_excel('D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Processed Data/Luas Tanah.xlsx')

## Pengeluaran per Kapita

In [221]:
Pengeluaran = pd.read_excel("D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Raw Data/Pengeluaran per Kapita.xlsx")
Pengeluaran.head()

,Kabupaten,Laki-laki - 2021,Laki-laki - 2022,Laki-laki - 2023,Perempuan - 2021,Perempuan - 2022,Perempuan - 2023
0,KALIMANTAN SELATAN,18148,18623,19193,8846,9071,9380
1,TANAH LAUT,17002,17581,18312,7884,8146,8458
2,KOTABARU,17911,18569,18997,6445,6722,6869
3,BANJAR,18731,18960,19580,11350,11484,11784
4,BARITO KUALA,14259,14772,15512,7828,8105,8496

In [222]:
# Menghapus baris pertama
Pengeluaran = Pengeluaran.drop(Pengeluaran.index[0])

# Membuat DataFrame baru dengan data tahun 2019
Pengeluaran_2023 = Pengeluaran[['Kabupaten', 'Laki-laki - 2023', 'Perempuan - 2023']]

# Menghapus "- 2023" dari nama kolom
Pengeluaran_2023 = Pengeluaran_2023.rename(columns={
    'Laki-laki - 2023': 'Pengeluaran Laki-laki',
    'Perempuan - 2023': 'Pengeluaran Perempuan'
})

# Mengubah nama kolom
Pengeluaran_2023['KABKOT'] = Pengeluaran_2023['Kabupaten']
Pengeluaran_2023 = Pengeluaran_2023.drop(columns=['Kabupaten'])

# Mengganti nilai di kolom 'KABKOT'
Pengeluaran_2023['KABKOT'] = Pengeluaran_2023['KABKOT'].replace({
    'KOTA BANJAR BARU': 'KOTA BANJARBARU'
})

Pengeluaran_2023.head()

   Pengeluaran Laki-laki  Pengeluaran Perempuan        KABKOT
1                  18312                   8458    TANAH LAUT
2                  18997                   6869      KOTABARU
3                  19580                  11784        BANJAR
4                  15512                   8496  BARITO KUALA
5                  19250                   7001         TAPIN

In [223]:
Pengeluaran_2023.to_excel('D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Processed Data/Pengeluaran per Kapitan per Gender.xlsx')

## Persebaran Lahan Kritis

In [224]:
Lahan = pd.read_excel("D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Raw Data/Lahan Kritis dan Sangat Kritis.xlsx")
Lahan.head()

,Kabupaten,Lahan Kritis - 2015,Lahan Kritis - 2018,Lahan Sangat Kritis - 2015,Lahan Sangat Kritis - 2018
0,KALIMANTAN SELATAN,508174.1,280133.81,132534.6,224810.12
1,TANAH LAUT,65639.9,33010.53,27502.4,12474.9
2,KOTABARU,166952.3,103,23726.7,19753.12
3,BANJAR,95977.8,33325.85,16598.5,72044.51
4,BARITO KUALA,19079.4,139.53,-,-

In [225]:
# Menghapus baris pertama
Lahan = Lahan.drop(Lahan.index[0])

# Membuat DataFrame baru dengan data tahun 2018
Lahan_2018 = Lahan[['Kabupaten', 'Lahan Kritis - 2018', 'Lahan Sangat Kritis - 2018']]

# Menghapus "- 2018" dari nama kolom
Lahan_2018 = Lahan_2018.rename(columns={
    'Lahan Kritis - 2018': 'Lahan Kritis',
    'Lahan Sangat Kritis - 2018': 'Lahan Sangat Kritis'
})

# Mengganti "-" dengan 0
Lahan_2018 = Lahan_2018.replace('-', 0)

# Mengubah nama kolom
Lahan_2018['KABKOT'] = Lahan_2018['Kabupaten']
Lahan_2018 = Lahan_2018.drop(columns=['Kabupaten'])

# Mengganti nilai di kolom 'KABKOT'
Lahan_2018['KABKOT'] = Lahan_2018['KABKOT'].replace({
    'KOTA BANJAR BARU': 'KOTA BANJARBARU'
})

Lahan_2018.head()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13788\2115069276.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Lahan_2018 = Lahan_2018.replace('-', 0)

   Lahan Kritis  Lahan Sangat Kritis        KABKOT
1      33010.53             12474.90    TANAH LAUT
2        103.00             19753.12      KOTABARU
3      33325.85             72044.51        BANJAR
4        139.53                 0.00  BARITO KUALA
5       6542.42             11565.38         TAPIN

In [226]:
Lahan_2018.to_excel('D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Processed Data/Lahan Kritis dan Sangat Kritis.xlsx')

## Kebakaran Hutan

In [227]:
Kebakaran = pd.read_excel("D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Raw Data/Kebakaran Hutan dan Lahan.xlsx")
Kebakaran.head()

,Lokasi/Tahun,Jumlah Kejadian Kebakaran Hutan dan Lahan (2018),Jumlah Luas Keseluruhan Hutan dan Lahan Terbakar (2018),Jumlah Kejadian Kebakaran Hutan (2019),Jumlah Luas Hutan Terbakar (2019),Jumlah Kejadian Kebakaran Lahan (2019),Jumlah Luas Lahan Terbakar (2019),Jumlah Kejadian Kebakaran Hutan (2020),Jumlah Luas Hutan Terbakar (2020),Jumlah Kejadian Kebakaran Lahan(2020),Jumlah Luas Lahan Terbakar (2020),Jumlah Kejadian Kebakaran Hutan (2021),Jumlah Luas Hutan Terbakar (2021),Jumlah Kejadian Kebakaran Lahan(2021),Jumlah Luas Lahan Terbakar (2021)
0,Kab. Tanah Laut,168,337.07,6,18.00,540,1262.15,0,0.00,2,6.10,0,0,47,411.45
1,Kab. Kotabaru,9,68.40,0,0.00,41,135.90,0,0.00,2,0.60,0,0,1,0.50
2,Kab. Banjar,160,854.40,5,67.50,241,1227.25,0,0.00,90,102.34,0,0,26,366.20
3,Kab. Barito Kuala,27,221.80,21,84.25,87,334.90,2,80.02,19,53.98,0,0,7,38.50
4,Kab. Tapin,88,764.15,0,0.00,202,930.56,0,0.00,7,3.04,0,0,37,212.00

In [228]:
print(Kebakaran.columns)

Index(['Lokasi/Tahun', 'Jumlah Kejadian Kebakaran Hutan  dan Lahan (2018)',
       'Jumlah Luas Keseluruhan Hutan dan Lahan Terbakar (2018)',
       'Jumlah Kejadian Kebakaran Hutan  (2019)',
       'Jumlah Luas Hutan Terbakar (2019)',
       'Jumlah Kejadian Kebakaran Lahan (2019)',
       'Jumlah Luas Lahan Terbakar (2019)',
       'Jumlah Kejadian Kebakaran Hutan (2020)',
       'Jumlah Luas Hutan Terbakar (2020)',
       'Jumlah Kejadian Kebakaran Lahan(2020)',
       'Jumlah Luas Lahan Terbakar (2020)',
       'Jumlah Kejadian Kebakaran Hutan (2021)',
       'Jumlah Luas Hutan Terbakar (2021)',
       'Jumlah Kejadian Kebakaran Lahan(2021)',
       'Jumlah Luas Lahan Terbakar (2021)'],
      dtype='object')

In [229]:
# Menghapus baris terakhir
Kebakaran = Kebakaran.drop(Kebakaran.index[-1])

# Mengubah huruf di kolom 'Lokasi/Tahun' menjadi uppercase dan hapus KAB.
Kebakaran['Lokasi/Tahun'] = Kebakaran['Lokasi/Tahun'].str.upper().str.replace('KAB. ', '', regex=False)

# Membuat DataFrame baru dengan data tahun 2021
Kebakaran_2021 = Kebakaran[['Lokasi/Tahun', 'Jumlah Kejadian Kebakaran Hutan (2021)',
                        'Jumlah Luas Hutan Terbakar (2021)',
                        'Jumlah Kejadian Kebakaran Lahan(2021)',
                        'Jumlah Luas Lahan Terbakar (2021)']]

# Menghapus "(2021)" dari nama kolom
Kebakaran_2021 = Kebakaran_2021.rename(columns={
    'Jumlah Kejadian Kebakaran Hutan (2021)': 'Kejadian Kebakaran Hutan',
    'Jumlah Luas Hutan Terbakar (2021)': 'Luas Hutan Terbakar',
    'Jumlah Kejadian Kebakaran Lahan(2021)': 'Kejadian Kebakaran Lahan',
    'Jumlah Luas Lahan Terbakar (2021)': 'Luas Lahan Terbakar'
})

# Mengubah nama kolom
Kebakaran_2021['KABKOT'] = Kebakaran_2021['Lokasi/Tahun']
Kebakaran_2021 = Kebakaran_2021.drop(columns=['Lokasi/Tahun'])
Kebakaran_2021.head()

,Kejadian Kebakaran Hutan,Luas Hutan Terbakar,Kejadian Kebakaran Lahan,Luas Lahan Terbakar,KABKOT
0,0,0,47,411.45,TANAH LAUT
1,0,0,1,0.50,KOTABARU
2,0,0,26,366.20,BANJAR
3,0,0,7,38.50,BARITO KUALA
4,0,0,37,212.00,TAPIN

In [230]:
Kebakaran_2021.to_excel('D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Real Data Used/Processed Data/Kejadian Kebakaran Hutan dan Lahan.xlsx')

# Akses seluruh data setelah Preprocessing

In [3]:
import os

# Mendapatkan daftar file dalam direktori kerja
dir = "D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Post Revisi/Processed Data"
files = os.listdir(dir)

# Mencetak daftar file
for file in files:
    print(file)

Akomodasi Hotel.xlsx
Data POI.xlsx
Data Potensi Wilayah.xlsx
Jarak Ibukota ke Provinsi.xlsx
Kejadian Kebakaran Hutan dan Lahan.xlsx
Kunjungan Wisata.xlsx
Lahan Kritis dan Sangat Kritis.xlsx
Luas Tanah.xlsx
Objek Wisata.xlsx
Penduduk Per Kabupaten.xlsx
Pengeluaran per Kapitan per Gender.xlsx

## Gabungkan seluruh dataset

In [7]:
# Loop untuk membaca file Excel
TOPSIS_index = [4, 1, 6, 9, 11, 5]
for i in TOPSIS_index:
    file_path = os.path.join(dir, files[(i-1)])
    globals()[f'df{i}'] = pd.read_excel(file_path, index_col=0)


Clustering_index = [10, 3, 8, 2, 7]
for i in Clustering_index:
    file_path = os.path.join(dir, files[(i-1)])
    globals()[f'df{i}'] = pd.read_excel(file_path, index_col=0)

In [9]:
# Menggabungkan DataFrame
TOPSIS_df = df4.merge(df1, on='KABKOT', how='outer')
for i in TOPSIS_index[2:5]:
    TOPSIS_df = TOPSIS_df.merge(globals()[f'df{i}'], on='KABKOT', how='outer')

Clustering_df = df10.merge(df3, on='KABKOT', how='outer')
for i in Clustering_index[2:4]:
    Clustering_df = Clustering_df.merge(globals()[f'df{i}'], on='KABKOT', how='outer')

In [10]:
TOPSIS_df.head

<bound method NDFrame.head of     Jarak (Km)               KABKOT  Hotel  Kamar  Tempat Tidur  Nusantara  \
0          202             BALANGAN      0      0             0      40127
1           40               BANJAR      6    572           837    2104383
2           45         BARITO KUALA      0      0             0     178044
3          135  HULU SUNGAI SELATAN      0      0             0     293234
4          165   HULU SUNGAI TENGAH      0      0             0     219597
5          190    HULU SUNGAI UTARA      0      0             0     103400
6           35      KOTA BANJARBARU     13    902          1322    2217478
7            0     KOTA BANJARMASIN     36   2788          4666    1178056
8          305             KOTABARU      2     81           127     763385
9          232             TABALONG      2    195           310    3092902
10         262          TANAH BUMBU      7    140           242     857429
11          65           TANAH LAUT      1     45            67     567506
12         113                TAPIN      0      0             0    1727420

    Mancanegara  Alam  Buatan  Budaya  Religi  Kuliner  Pengeluaran Laki-laki  \
0            20    23      14       1       1        0                  16692
1          1063    14       7       0       2        0                  19580
2            78     5       9       0       1        0                  15512
3           613     4      11       0       0        0                  20057
4            33     2       9       0       0        0                  14139
5             0     4       2       1       5        0                  15097
6          1666     1      14       0       0        0                  20702
7          2487     3      10       0       4        4                  19316
8            67     6       0       0       1        0                  18997
9         44754    29      28       2       6        0                  19622
10          389    15       0       0       0        0                  20009
11            8    26       4       0       0        0                  18312
12           19    14       4       0       8        1                  19250

    Pengeluaran Perempuan
0                   11501
1                   11784
2                    8496
3                    9255
4                   12388
5                    9146
6                   13866
7                   14171
8                    6869
9                    7382
10                   7600
11                   8458
12                   7001  >

In [11]:
KABKOT = TOPSIS_df.pop('KABKOT')
TOPSIS_df.insert(0, 'KABKOT', KABKOT)

In [12]:
Clustering_df.head

<bound method NDFrame.head of     Laki-Laki  Perempuan               KABKOT  JUMLAH DESA  \
0       69.83      68.28             BALANGAN          157
1      303.10     297.54               BANJAR          290
2      167.67     163.32         BARITO KUALA          201
3      120.00     118.78  HULU SUNGAI SELATAN          148
4      135.24     133.51   HULU SUNGAI TENGAH          169
5      118.67     118.44    HULU SUNGAI UTARA          219
6      137.30     136.17      KOTA BANJARBARU           20
7      334.61     334.15     KOTA BANJARMASIN           52
8      176.80     166.88             KOTABARU          202
9      135.27     131.62             TABALONG          131
10     175.10     167.26          TANAH BUMBU          150
11     186.62     178.37           TANAH LAUT          135
12     100.48      98.39                TAPIN          135

    JUMLAH DESA TERDATA   JUMLAH LUAS WILAYAH   JUMLAH PENETAPAN BATAS  \
0                    38               859.436                       18
1                    51               630.843                       31
2                   121               108.388                       78
3                   131           1320546.000                      107
4                    79               927.332                       68
5                   181           1453685.000                      150
6                    20               592.305                       18
7                    52               815.554                       43
8                   142           1958382.000                      109
9                    64               712.902                       53
10                  146           1171750.000                      128
11                   46           1356790.000                       22
12                  131           2460916.000                       90

     JUMLAH PETA BATAS    OGH    KPMK  ...  Swimming Pool  Tourism Site  \
0                   28      0       0  ...              0             0
1                   41      0  203750  ...              0             4
2                  108  95049       0  ...              0             1
3                  127  28750   12187  ...              1             0
4                   69  18437       0  ...              0             0
5                  167   7187       0  ...              0             1
6                   20      0       0  ...              1             5
7                   51      0       0  ...              0             4
8                  117  42187   95678  ...              0             0
9                   56      0   93125  ...              0             1
10                 138      0  365377  ...              0             0
11                  40      0  154250  ...              0             1
12                 115      0    4062  ...              1             1

    Tourist Office  Travel Agency Tutoring/Computer/Language  \
0                0              0                          0
1                0              0                          0
2                0              0                          0
3                1              0                          0
4                0              0                          0
5                1              0                          0
6                0              1                          0
7                0             88                         14
8                0              0                          0
9                0              0                          0
10               0              0                          0
11               0              0                          0
12               0              0                          0

    University/College  Vantage Point  Warehouse  Watches/Glasses/Optics  Zoo
0                    0              2          0                       0    0
1                    1             12          1                       0    0
2                    0              0          0                       0    0
3                    0              0          0                       0    0
4                    0              1          0                       0    0
5                    0              0          0                       0    0
6                    1              0          0                       0    0
7                   22              0          0                       9    1
8                    0             21          0                       0    0
9                    0              1          0                       0    0
10                   0              2          0                       0    0
11                   0             15          0                       0    0
12                   0              0          0                       0    0

[13 rows x 100 columns]>

In [13]:
KABKOT = Clustering_df.pop('KABKOT')
Clustering_df.insert(0, 'KABKOT', KABKOT)

In [14]:
TOPSIS_df.to_excel('D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Post Revisi/TOPSIS Data Frame.xlsx')
Clustering_df.to_excel('D:/Kerjaan/Project P64180125 (k-Means, DBSCAN and TOPSIS in Python)/Post Revisi/Clustering Data Frame.xlsx')